import Head from 'next/head'
import Navigation from '../components/Navigation'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Prime Properties</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation/>

      <main>
       
      </main>

    </div>
  )
}
