import Head from "next/head";
import Navigation from "../components/Navigation";
import Banner from "../components/Banner";
import RecentProperties from "../components/RecentProperties";
import ImageBanner from "../components/ImageBanner";
import Locations from "../components/Locations";
import ColorBanner from "../components/ColorBanner";
import Testimonials from "../components/Testimonials";
import Contact from "../components/Contact";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Prime Properties</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />

      <main>
        <Banner />
        <RecentProperties />
        <ImageBanner />
        <Locations />
        <ColorBanner />
        <Testimonials />
        <Contact />
        <Footer />
      </main>
    </div>
  );
}
