import Head from "next/head";
import Navigation from "../components/Navigation";
import Banner from "../components/Banner";
import RecentProperties from "../components/RecentProperties";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Prime Properties</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />

      <main>
        <Banner />
        <RecentProperties />
      </main>
    </div>
  );
}
