name: Build Website and Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  
  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.1.1
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,md}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [prettier]

    steps:
      - name: Get latest code
        uses: actions/checkout@v2.3.4

      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install NPM Modules
        run: npm ci

      - name: Lint Frontend
        run: npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - name: Get latest code
        uses: actions/checkout@v2.3.4

      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install NPM Modules
        run: npm ci

      - name: Build Frontend
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    name: "Deploy front-end"
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/

      - name: "Deploy to Vercel"
        run: |
          prodRun=""
          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            prodRun="--prod"
          fi

          npx vercel --token ${VERCEL_TOKEN} $prodRun
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
