name: Build Website and Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  build:

    name: Build NextJs App
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.4

    - name: Use Node.js v16.13.0
      uses: actions/setup-node@v16.13.0
      with:
        node-version: '16.13.0'
      
    - name: Install NPM Modules
      run: npm ci

    - name: Build Frontend
      run: npm run build